//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesConsoleClient.EmployeesServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeInfo", Namespace="http://schemas.datacontract.org/2004/07/EmployeesConsoleService")]
    [System.SerializableAttribute()]
    public partial class EmployeeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeesServiceReference.IWCFemployeesService")]
    public interface IWCFemployeesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFemployeesService/EmployeesIDs", ReplyAction="http://tempuri.org/IWCFemployeesService/EmployeesIDsResponse")]
        System.Collections.Generic.List<int> EmployeesIDs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFemployeesService/EmployeesIDs", ReplyAction="http://tempuri.org/IWCFemployeesService/EmployeesIDsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> EmployeesIDsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFemployeesService/EmpInfo", ReplyAction="http://tempuri.org/IWCFemployeesService/EmpInfoResponse")]
        EmployeesConsoleClient.EmployeesServiceReference.EmployeeInfo EmpInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFemployeesService/EmpInfo", ReplyAction="http://tempuri.org/IWCFemployeesService/EmpInfoResponse")]
        System.Threading.Tasks.Task<EmployeesConsoleClient.EmployeesServiceReference.EmployeeInfo> EmpInfoAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFemployeesServiceChannel : EmployeesConsoleClient.EmployeesServiceReference.IWCFemployeesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFemployeesServiceClient : System.ServiceModel.ClientBase<EmployeesConsoleClient.EmployeesServiceReference.IWCFemployeesService>, EmployeesConsoleClient.EmployeesServiceReference.IWCFemployeesService {
        
        public WCFemployeesServiceClient() {
        }
        
        public WCFemployeesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFemployeesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFemployeesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFemployeesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<int> EmployeesIDs() {
            return base.Channel.EmployeesIDs();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> EmployeesIDsAsync() {
            return base.Channel.EmployeesIDsAsync();
        }
        
        public EmployeesConsoleClient.EmployeesServiceReference.EmployeeInfo EmpInfo(int id) {
            return base.Channel.EmpInfo(id);
        }
        
        public System.Threading.Tasks.Task<EmployeesConsoleClient.EmployeesServiceReference.EmployeeInfo> EmpInfoAsync(int id) {
            return base.Channel.EmpInfoAsync(id);
        }
    }
}
