//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAssistant.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KiskereskedoEntities : DbContext
    {
        public KiskereskedoEntities()
            : base("name=KiskereskedoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AruKategoria> AruKategoriak { get; set; }
        public virtual DbSet<AruKeszlet> AruKeszletek { get; set; }
        public virtual DbSet<Ertekesites> Ertekesitesek { get; set; }
        public virtual DbSet<ErtekesitesReszlet> ErtekesitesReszletek { get; set; }
    }
}
