//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileModel
    {
        public System.Guid UserID { get; set; }
        public string Nick { get; set; }
        public string Password { get; set; }
        public byte[] Image { get; set; }
        public bool LoggedIn { get; set; }
        public string Message { get; set; }
    }
}
